### ISSUE TITLE
 Cannot read property getURL of undefined

### ISSUE THREAD

**Issue by alaa137** [jeromewu/tesseract.js-chrome-extension#1]
It's not working for me in Chrome 74.0.3729.157:

> main.js:7 Uncaught TypeError: Cannot read property 'getURL' of undefined
> at HTMLButtonElement.doOCR (main.js:7)

**Comment by jeromewu** [comment]
Mine is Version 74.0.3729.169 (Official Build) (64-bit) for your reference.

Can you try to identify whether chrome.runtime exists?

You can paste output from:

```javascript
console.log(typeof chrome);
console.log(object.keys(chrome))
console.log(typeof chrome.runtime);
```

**Comment by alaa137** [comment]
```
console.log(typeof chrome);
console.log(object.keys(chrome))
console.log(typeof chrome.runtime);
```

> VM347:1 object
> VM347:2 Uncaught ReferenceError: object is not defined
>     at <anonymous>:2:13
> (anonymous) @ VM347:2

**Comment by jeromewu** [comment]
Sorry there is typo:

```javascript
console.log(Object.keys(chrome));
```

**Comment by alaa137** [comment]
Output:
```
console.log(Object.keys(chrome));
VM356:1 (4) ["loadTimes", "csi", "app", "runtime"]
```

**Comment by jeromewu** [comment]
Oh, I think you run this code in the wrong way.

Please check the description here: https://github.com/jeromewu/tesseract.js-chrome-extension#install

**Comment by alaa137** [comment]
My bad. It's working!

**Comment by kartashowRoman** [comment]
Hello! I have installed the extension but on button click no OCR occurs... nothing happens. What might be the reason? I just clone the repo and uploaded the files. The popup opens but that's all
